//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.11.2
//     from Assets/ShrekInputActions.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

public partial class @ShrekInputActions: IInputActionCollection2, IDisposable
{
    public InputActionAsset asset { get; }
    public @ShrekInputActions()
    {
        asset = InputActionAsset.FromJson(@"{
    ""name"": ""ShrekInputActions"",
    ""maps"": [
        {
            ""name"": ""Jugador"",
            ""id"": ""2db4bc53-4c5d-4184-a58c-a80ee96b9523"",
            ""actions"": [
                {
                    ""name"": ""Saltar"",
                    ""type"": ""Button"",
                    ""id"": ""608b52c8-f845-4564-8db3-29c9d75a43ae"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""Moverse"",
                    ""type"": ""PassThrough"",
                    ""id"": ""f8d0d2ce-5862-4691-9ff1-66c432e92d45"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Sprint"",
                    ""type"": ""Button"",
                    ""id"": ""6c92c3e6-5ea9-4724-b158-149e99a2b2ad"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Crouch"",
                    ""type"": ""Button"",
                    ""id"": ""3d5687b5-8938-4e81-a928-236dbf73f2c5"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""CambiarCamara"",
                    ""type"": ""Button"",
                    ""id"": ""eee505a7-c0dc-4aa8-82f9-4e7619d408a4"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Disparo"",
                    ""type"": ""Button"",
                    ""id"": ""cad1edb7-0e19-4441-aaef-a79af535c673"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Mirar"",
                    ""type"": ""Value"",
                    ""id"": ""e8997b8c-3126-49d4-b5f9-7038e7826531"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""2273882f-9007-4a29-bcbf-752659b4638a"",
                    ""path"": ""<Keyboard>/space"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Saltar"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""2D Vector"",
                    ""id"": ""613e86f2-d051-4ab9-9bca-3588ccc91371"",
                    ""path"": ""2DVector"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Moverse"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""up"",
                    ""id"": ""ba766056-2279-41a6-a7ac-ca6573c1453d"",
                    ""path"": ""<Keyboard>/w"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": "";Keyboard"",
                    ""action"": ""Moverse"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""down"",
                    ""id"": ""b3a489ee-1396-4de4-83a9-510db6bc4d2a"",
                    ""path"": ""<Keyboard>/s"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": "";Keyboard"",
                    ""action"": ""Moverse"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""left"",
                    ""id"": ""dfeb55ea-56fa-457e-9a9b-b8ff4a425045"",
                    ""path"": ""<Keyboard>/a"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": "";Keyboard"",
                    ""action"": ""Moverse"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""right"",
                    ""id"": ""9efe50e0-d009-4f1c-be11-a97087b6eae4"",
                    ""path"": ""<Keyboard>/d"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": "";Keyboard"",
                    ""action"": ""Moverse"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": """",
                    ""id"": ""b0645391-b609-4060-8a86-943fd7f17ef2"",
                    ""path"": ""<Keyboard>/shift"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Sprint"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""f16efb95-cc5b-492a-97f3-a7526d15298a"",
                    ""path"": ""<Keyboard>/v"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Crouch"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""ab01a30d-cddd-452b-9bfe-54cfac2aba18"",
                    ""path"": ""<Keyboard>/c"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""CambiarCamara"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""b12447f7-0f9b-4031-bd4d-94a956317f84"",
                    ""path"": ""<Mouse>/leftButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Disparo"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""06fdc4a1-bb27-4e22-a1d8-00151f359716"",
                    ""path"": ""<Mouse>/delta"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Mirar"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": [
        {
            ""name"": ""Keyboard"",
            ""bindingGroup"": ""Keyboard"",
            ""devices"": [
                {
                    ""devicePath"": ""<Keyboard>"",
                    ""isOptional"": false,
                    ""isOR"": false
                }
            ]
        }
    ]
}");
        // Jugador
        m_Jugador = asset.FindActionMap("Jugador", throwIfNotFound: true);
        m_Jugador_Saltar = m_Jugador.FindAction("Saltar", throwIfNotFound: true);
        m_Jugador_Moverse = m_Jugador.FindAction("Moverse", throwIfNotFound: true);
        m_Jugador_Sprint = m_Jugador.FindAction("Sprint", throwIfNotFound: true);
        m_Jugador_Crouch = m_Jugador.FindAction("Crouch", throwIfNotFound: true);
        m_Jugador_CambiarCamara = m_Jugador.FindAction("CambiarCamara", throwIfNotFound: true);
        m_Jugador_Disparo = m_Jugador.FindAction("Disparo", throwIfNotFound: true);
        m_Jugador_Mirar = m_Jugador.FindAction("Mirar", throwIfNotFound: true);
    }

    ~@ShrekInputActions()
    {
        UnityEngine.Debug.Assert(!m_Jugador.enabled, "This will cause a leak and performance issues, ShrekInputActions.Jugador.Disable() has not been called.");
    }

    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    public void Enable()
    {
        asset.Enable();
    }

    public void Disable()
    {
        asset.Disable();
    }

    public IEnumerable<InputBinding> bindings => asset.bindings;

    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }

    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // Jugador
    private readonly InputActionMap m_Jugador;
    private List<IJugadorActions> m_JugadorActionsCallbackInterfaces = new List<IJugadorActions>();
    private readonly InputAction m_Jugador_Saltar;
    private readonly InputAction m_Jugador_Moverse;
    private readonly InputAction m_Jugador_Sprint;
    private readonly InputAction m_Jugador_Crouch;
    private readonly InputAction m_Jugador_CambiarCamara;
    private readonly InputAction m_Jugador_Disparo;
    private readonly InputAction m_Jugador_Mirar;
    public struct JugadorActions
    {
        private @ShrekInputActions m_Wrapper;
        public JugadorActions(@ShrekInputActions wrapper) { m_Wrapper = wrapper; }
        public InputAction @Saltar => m_Wrapper.m_Jugador_Saltar;
        public InputAction @Moverse => m_Wrapper.m_Jugador_Moverse;
        public InputAction @Sprint => m_Wrapper.m_Jugador_Sprint;
        public InputAction @Crouch => m_Wrapper.m_Jugador_Crouch;
        public InputAction @CambiarCamara => m_Wrapper.m_Jugador_CambiarCamara;
        public InputAction @Disparo => m_Wrapper.m_Jugador_Disparo;
        public InputAction @Mirar => m_Wrapper.m_Jugador_Mirar;
        public InputActionMap Get() { return m_Wrapper.m_Jugador; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(JugadorActions set) { return set.Get(); }
        public void AddCallbacks(IJugadorActions instance)
        {
            if (instance == null || m_Wrapper.m_JugadorActionsCallbackInterfaces.Contains(instance)) return;
            m_Wrapper.m_JugadorActionsCallbackInterfaces.Add(instance);
            @Saltar.started += instance.OnSaltar;
            @Saltar.performed += instance.OnSaltar;
            @Saltar.canceled += instance.OnSaltar;
            @Moverse.started += instance.OnMoverse;
            @Moverse.performed += instance.OnMoverse;
            @Moverse.canceled += instance.OnMoverse;
            @Sprint.started += instance.OnSprint;
            @Sprint.performed += instance.OnSprint;
            @Sprint.canceled += instance.OnSprint;
            @Crouch.started += instance.OnCrouch;
            @Crouch.performed += instance.OnCrouch;
            @Crouch.canceled += instance.OnCrouch;
            @CambiarCamara.started += instance.OnCambiarCamara;
            @CambiarCamara.performed += instance.OnCambiarCamara;
            @CambiarCamara.canceled += instance.OnCambiarCamara;
            @Disparo.started += instance.OnDisparo;
            @Disparo.performed += instance.OnDisparo;
            @Disparo.canceled += instance.OnDisparo;
            @Mirar.started += instance.OnMirar;
            @Mirar.performed += instance.OnMirar;
            @Mirar.canceled += instance.OnMirar;
        }

        private void UnregisterCallbacks(IJugadorActions instance)
        {
            @Saltar.started -= instance.OnSaltar;
            @Saltar.performed -= instance.OnSaltar;
            @Saltar.canceled -= instance.OnSaltar;
            @Moverse.started -= instance.OnMoverse;
            @Moverse.performed -= instance.OnMoverse;
            @Moverse.canceled -= instance.OnMoverse;
            @Sprint.started -= instance.OnSprint;
            @Sprint.performed -= instance.OnSprint;
            @Sprint.canceled -= instance.OnSprint;
            @Crouch.started -= instance.OnCrouch;
            @Crouch.performed -= instance.OnCrouch;
            @Crouch.canceled -= instance.OnCrouch;
            @CambiarCamara.started -= instance.OnCambiarCamara;
            @CambiarCamara.performed -= instance.OnCambiarCamara;
            @CambiarCamara.canceled -= instance.OnCambiarCamara;
            @Disparo.started -= instance.OnDisparo;
            @Disparo.performed -= instance.OnDisparo;
            @Disparo.canceled -= instance.OnDisparo;
            @Mirar.started -= instance.OnMirar;
            @Mirar.performed -= instance.OnMirar;
            @Mirar.canceled -= instance.OnMirar;
        }

        public void RemoveCallbacks(IJugadorActions instance)
        {
            if (m_Wrapper.m_JugadorActionsCallbackInterfaces.Remove(instance))
                UnregisterCallbacks(instance);
        }

        public void SetCallbacks(IJugadorActions instance)
        {
            foreach (var item in m_Wrapper.m_JugadorActionsCallbackInterfaces)
                UnregisterCallbacks(item);
            m_Wrapper.m_JugadorActionsCallbackInterfaces.Clear();
            AddCallbacks(instance);
        }
    }
    public JugadorActions @Jugador => new JugadorActions(this);
    private int m_KeyboardSchemeIndex = -1;
    public InputControlScheme KeyboardScheme
    {
        get
        {
            if (m_KeyboardSchemeIndex == -1) m_KeyboardSchemeIndex = asset.FindControlSchemeIndex("Keyboard");
            return asset.controlSchemes[m_KeyboardSchemeIndex];
        }
    }
    public interface IJugadorActions
    {
        void OnSaltar(InputAction.CallbackContext context);
        void OnMoverse(InputAction.CallbackContext context);
        void OnSprint(InputAction.CallbackContext context);
        void OnCrouch(InputAction.CallbackContext context);
        void OnCambiarCamara(InputAction.CallbackContext context);
        void OnDisparo(InputAction.CallbackContext context);
        void OnMirar(InputAction.CallbackContext context);
    }
}
